/// <reference path="core.d.ts" />
/// <reference path="network.d.ts" />
declare namespace bluetooth {
	interface QBluetooth_ITF {
		QBluetooth_PTR():QBluetooth;
	}

	class QBluetooth {
		___pointer: number;
		QBluetooth_PTR():QBluetooth;
		Pointer():number;
		SetPointer(p:number):void;
		DestroyQBluetooth():void;
	}
	function NewQBluetoothFromPointer(ptr:number):QBluetooth;
	const QBluetooth__AttAuthorizationRequired: number;
	const QBluetooth__AttAuthenticationRequired: number;
	const QBluetooth__AttEncryptionRequired: number;
	const QBluetooth__NoSecurity: number;
	const QBluetooth__Authorization: number;
	const QBluetooth__Authentication: number;
	const QBluetooth__Encryption: number;
	const QBluetooth__Secure: number;
	interface QBluetoothAddress_ITF {
		QBluetoothAddress_PTR():QBluetoothAddress;
	}

	class QBluetoothAddress {
		___pointer: number;
		QBluetoothAddress_PTR():QBluetoothAddress;
		Pointer():number;
		SetPointer(p:number):void;
		Clear():void;
		IsNull():boolean;
		ToString():string;
		ToUInt64():number;
		DestroyQBluetoothAddress():void;
	}
	function NewQBluetoothAddressFromPointer(ptr:number):QBluetoothAddress;
	function NewQBluetoothAddress():QBluetoothAddress;
	function NewQBluetoothAddress2(address:number):QBluetoothAddress;
	function NewQBluetoothAddress3(address:string):QBluetoothAddress;
	function NewQBluetoothAddress4(other:QBluetoothAddress_ITF):QBluetoothAddress;
	interface QBluetoothDeviceDiscoveryAgent_ITF extends core.QObject_ITF {
		QBluetoothDeviceDiscoveryAgent_PTR():QBluetoothDeviceDiscoveryAgent;
	}

	class QBluetoothDeviceDiscoveryAgent extends core.QObject {
		___pointer: number;
		QBluetoothDeviceDiscoveryAgent_PTR():QBluetoothDeviceDiscoveryAgent;
		Pointer():number;
		SetPointer(p:number):void;
		ConnectCanceled(f:()=>void):void;
		DisconnectCanceled():void;
		Canceled():void;
		ConnectDeviceDiscovered(f:(info:QBluetoothDeviceInfo)=>void):void;
		DisconnectDeviceDiscovered():void;
		DeviceDiscovered(info:QBluetoothDeviceInfo_ITF):void;
		ConnectDeviceUpdated(f:(info:QBluetoothDeviceInfo,updatedFields:number)=>void):void;
		DisconnectDeviceUpdated():void;
		DeviceUpdated(info:QBluetoothDeviceInfo_ITF,updatedFields:number):void;
		DiscoveredDevices():QBluetoothDeviceInfo[];
		Error():number;
		ConnectError2(f:(error:number)=>void):void;
		DisconnectError2():void;
		Error2(error:number):void;
		ErrorString():string;
		ConnectFinished(f:()=>void):void;
		DisconnectFinished():void;
		Finished():void;
		InquiryType():number;
		IsActive():boolean;
		LowEnergyDiscoveryTimeout():number;
		SetInquiryType(ty:number):void;
		SetLowEnergyDiscoveryTimeout(timeout:number):void;
		ConnectStart(f:()=>void):void;
		DisconnectStart():void;
		Start():void;
		StartDefault():void;
		ConnectStart2(f:(methods:number)=>void):void;
		DisconnectStart2():void;
		Start2(methods:number):void;
		Start2Default(methods:number):void;
		ConnectStop(f:()=>void):void;
		DisconnectStop():void;
		Stop():void;
		StopDefault():void;
		SupportedDiscoveryMethods():number;
		ConnectDestroyQBluetoothDeviceDiscoveryAgent(f:()=>void):void;
		DisconnectDestroyQBluetoothDeviceDiscoveryAgent():void;
		DestroyQBluetoothDeviceDiscoveryAgent():void;
		DestroyQBluetoothDeviceDiscoveryAgentDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothDeviceDiscoveryAgentFromPointer(ptr:number):QBluetoothDeviceDiscoveryAgent;
	function NewQBluetoothDeviceDiscoveryAgent(parent:core.QObject_ITF):QBluetoothDeviceDiscoveryAgent;
	function NewQBluetoothDeviceDiscoveryAgent2(deviceAdapter:QBluetoothAddress_ITF,parent:core.QObject_ITF):QBluetoothDeviceDiscoveryAgent;
	function QBluetoothDeviceDiscoveryAgent_SupportedDiscoveryMethods():number;
	const QBluetoothDeviceDiscoveryAgent__NoError: number;
	const QBluetoothDeviceDiscoveryAgent__InputOutputError: number;
	const QBluetoothDeviceDiscoveryAgent__PoweredOffError: number;
	const QBluetoothDeviceDiscoveryAgent__InvalidBluetoothAdapterError: number;
	const QBluetoothDeviceDiscoveryAgent__UnsupportedPlatformError: number;
	const QBluetoothDeviceDiscoveryAgent__UnsupportedDiscoveryMethod: number;
	const QBluetoothDeviceDiscoveryAgent__UnknownError: number;
	const QBluetoothDeviceDiscoveryAgent__GeneralUnlimitedInquiry: number;
	const QBluetoothDeviceDiscoveryAgent__LimitedInquiry: number;
	const QBluetoothDeviceDiscoveryAgent__NoMethod: number;
	const QBluetoothDeviceDiscoveryAgent__ClassicMethod: number;
	const QBluetoothDeviceDiscoveryAgent__LowEnergyMethod: number;
	interface QBluetoothDeviceInfo_ITF {
		QBluetoothDeviceInfo_PTR():QBluetoothDeviceInfo;
	}

	class QBluetoothDeviceInfo {
		___pointer: number;
		QBluetoothDeviceInfo_PTR():QBluetoothDeviceInfo;
		Pointer():number;
		SetPointer(p:number):void;
		Address():QBluetoothAddress;
		CoreConfigurations():number;
		DeviceUuid():QBluetoothUuid;
		IsCached():boolean;
		IsValid():boolean;
		MajorDeviceClass():number;
		ManufacturerIds():number[];
		MinorDeviceClass():string;
		Name():string;
		Rssi():number;
		ServiceClasses():number;
		SetCached(cached:boolean):void;
		SetCoreConfigurations(coreConfigs:number):void;
		SetDeviceUuid(uuid:QBluetoothUuid_ITF):void;
		SetManufacturerData(manufacturerId:number,data:core.QByteArray_ITF):boolean;
		SetRssi(sign:number):void;
		SetServiceUuids2(uuids:QBluetoothUuid[]):void;
		DestroyQBluetoothDeviceInfo():void;
	}
	function NewQBluetoothDeviceInfoFromPointer(ptr:number):QBluetoothDeviceInfo;
	function NewQBluetoothDeviceInfo():QBluetoothDeviceInfo;
	function NewQBluetoothDeviceInfo2(address:QBluetoothAddress_ITF,name:string,classOfDevice:number):QBluetoothDeviceInfo;
	function NewQBluetoothDeviceInfo3(uuid:QBluetoothUuid_ITF,name:string,classOfDevice:number):QBluetoothDeviceInfo;
	function NewQBluetoothDeviceInfo4(other:QBluetoothDeviceInfo_ITF):QBluetoothDeviceInfo;
	const QBluetoothDeviceInfo__MiscellaneousDevice: number;
	const QBluetoothDeviceInfo__ComputerDevice: number;
	const QBluetoothDeviceInfo__PhoneDevice: number;
	const QBluetoothDeviceInfo__LANAccessDevice: number;
	const QBluetoothDeviceInfo__NetworkDevice: number;
	const QBluetoothDeviceInfo__AudioVideoDevice: number;
	const QBluetoothDeviceInfo__PeripheralDevice: number;
	const QBluetoothDeviceInfo__ImagingDevice: number;
	const QBluetoothDeviceInfo__WearableDevice: number;
	const QBluetoothDeviceInfo__ToyDevice: number;
	const QBluetoothDeviceInfo__HealthDevice: number;
	const QBluetoothDeviceInfo__UncategorizedDevice: number;
	const QBluetoothDeviceInfo__UncategorizedMiscellaneous: number;
	const QBluetoothDeviceInfo__UncategorizedComputer: number;
	const QBluetoothDeviceInfo__DesktopComputer: number;
	const QBluetoothDeviceInfo__ServerComputer: number;
	const QBluetoothDeviceInfo__LaptopComputer: number;
	const QBluetoothDeviceInfo__HandheldClamShellComputer: number;
	const QBluetoothDeviceInfo__HandheldComputer: number;
	const QBluetoothDeviceInfo__WearableComputer: number;
	const QBluetoothDeviceInfo__UncategorizedPhone: number;
	const QBluetoothDeviceInfo__CellularPhone: number;
	const QBluetoothDeviceInfo__CordlessPhone: number;
	const QBluetoothDeviceInfo__SmartPhone: number;
	const QBluetoothDeviceInfo__WiredModemOrVoiceGatewayPhone: number;
	const QBluetoothDeviceInfo__CommonIsdnAccessPhone: number;
	const QBluetoothDeviceInfo__NetworkFullService: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorOne: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorTwo: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorThree: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorFour: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorFive: number;
	const QBluetoothDeviceInfo__NetworkLoadFactorSix: number;
	const QBluetoothDeviceInfo__NetworkNoService: number;
	const QBluetoothDeviceInfo__UncategorizedAudioVideoDevice: number;
	const QBluetoothDeviceInfo__WearableHeadsetDevice: number;
	const QBluetoothDeviceInfo__HandsFreeDevice: number;
	const QBluetoothDeviceInfo__Microphone: number;
	const QBluetoothDeviceInfo__Loudspeaker: number;
	const QBluetoothDeviceInfo__Headphones: number;
	const QBluetoothDeviceInfo__PortableAudioDevice: number;
	const QBluetoothDeviceInfo__CarAudio: number;
	const QBluetoothDeviceInfo__SetTopBox: number;
	const QBluetoothDeviceInfo__HiFiAudioDevice: number;
	const QBluetoothDeviceInfo__Vcr: number;
	const QBluetoothDeviceInfo__VideoCamera: number;
	const QBluetoothDeviceInfo__Camcorder: number;
	const QBluetoothDeviceInfo__VideoMonitor: number;
	const QBluetoothDeviceInfo__VideoDisplayAndLoudspeaker: number;
	const QBluetoothDeviceInfo__VideoConferencing: number;
	const QBluetoothDeviceInfo__GamingDevice: number;
	const QBluetoothDeviceInfo__UncategorizedPeripheral: number;
	const QBluetoothDeviceInfo__KeyboardPeripheral: number;
	const QBluetoothDeviceInfo__PointingDevicePeripheral: number;
	const QBluetoothDeviceInfo__KeyboardWithPointingDevicePeripheral: number;
	const QBluetoothDeviceInfo__JoystickPeripheral: number;
	const QBluetoothDeviceInfo__GamepadPeripheral: number;
	const QBluetoothDeviceInfo__RemoteControlPeripheral: number;
	const QBluetoothDeviceInfo__SensingDevicePeripheral: number;
	const QBluetoothDeviceInfo__DigitizerTabletPeripheral: number;
	const QBluetoothDeviceInfo__CardReaderPeripheral: number;
	const QBluetoothDeviceInfo__UncategorizedImagingDevice: number;
	const QBluetoothDeviceInfo__ImageDisplay: number;
	const QBluetoothDeviceInfo__ImageCamera: number;
	const QBluetoothDeviceInfo__ImageScanner: number;
	const QBluetoothDeviceInfo__ImagePrinter: number;
	const QBluetoothDeviceInfo__UncategorizedWearableDevice: number;
	const QBluetoothDeviceInfo__WearableWristWatch: number;
	const QBluetoothDeviceInfo__WearablePager: number;
	const QBluetoothDeviceInfo__WearableJacket: number;
	const QBluetoothDeviceInfo__WearableHelmet: number;
	const QBluetoothDeviceInfo__WearableGlasses: number;
	const QBluetoothDeviceInfo__UncategorizedToy: number;
	const QBluetoothDeviceInfo__ToyRobot: number;
	const QBluetoothDeviceInfo__ToyVehicle: number;
	const QBluetoothDeviceInfo__ToyDoll: number;
	const QBluetoothDeviceInfo__ToyController: number;
	const QBluetoothDeviceInfo__ToyGame: number;
	const QBluetoothDeviceInfo__UncategorizedHealthDevice: number;
	const QBluetoothDeviceInfo__HealthBloodPressureMonitor: number;
	const QBluetoothDeviceInfo__HealthThermometer: number;
	const QBluetoothDeviceInfo__HealthWeightScale: number;
	const QBluetoothDeviceInfo__HealthGlucoseMeter: number;
	const QBluetoothDeviceInfo__HealthPulseOximeter: number;
	const QBluetoothDeviceInfo__HealthDataDisplay: number;
	const QBluetoothDeviceInfo__HealthStepCounter: number;
	const QBluetoothDeviceInfo__NoService: number;
	const QBluetoothDeviceInfo__PositioningService: number;
	const QBluetoothDeviceInfo__NetworkingService: number;
	const QBluetoothDeviceInfo__RenderingService: number;
	const QBluetoothDeviceInfo__CapturingService: number;
	const QBluetoothDeviceInfo__ObjectTransferService: number;
	const QBluetoothDeviceInfo__AudioService: number;
	const QBluetoothDeviceInfo__TelephonyService: number;
	const QBluetoothDeviceInfo__InformationService: number;
	const QBluetoothDeviceInfo__AllServices: number;
	const QBluetoothDeviceInfo__DataComplete: number;
	const QBluetoothDeviceInfo__DataIncomplete: number;
	const QBluetoothDeviceInfo__DataUnavailable: number;
	const QBluetoothDeviceInfo__None: number;
	const QBluetoothDeviceInfo__RSSI: number;
	const QBluetoothDeviceInfo__ManufacturerData: number;
	const QBluetoothDeviceInfo__All: number;
	const QBluetoothDeviceInfo__UnknownCoreConfiguration: number;
	const QBluetoothDeviceInfo__LowEnergyCoreConfiguration: number;
	const QBluetoothDeviceInfo__BaseRateCoreConfiguration: number;
	const QBluetoothDeviceInfo__BaseRateAndLowEnergyCoreConfiguration: number;
	interface QBluetoothHostInfo_ITF {
		QBluetoothHostInfo_PTR():QBluetoothHostInfo;
	}

	class QBluetoothHostInfo {
		___pointer: number;
		QBluetoothHostInfo_PTR():QBluetoothHostInfo;
		Pointer():number;
		SetPointer(p:number):void;
		Address():QBluetoothAddress;
		Name():string;
		SetAddress(address:QBluetoothAddress_ITF):void;
		SetName(name:string):void;
		DestroyQBluetoothHostInfo():void;
	}
	function NewQBluetoothHostInfoFromPointer(ptr:number):QBluetoothHostInfo;
	function NewQBluetoothHostInfo():QBluetoothHostInfo;
	function NewQBluetoothHostInfo2(other:QBluetoothHostInfo_ITF):QBluetoothHostInfo;
	interface QBluetoothLocalDevice_ITF extends core.QObject_ITF {
		QBluetoothLocalDevice_PTR():QBluetoothLocalDevice;
	}

	class QBluetoothLocalDevice extends core.QObject {
		___pointer: number;
		QBluetoothLocalDevice_PTR():QBluetoothLocalDevice;
		Pointer():number;
		SetPointer(p:number):void;
		Address():QBluetoothAddress;
		AllDevices():QBluetoothHostInfo[];
		ConnectedDevices():QBluetoothAddress[];
		ConnectDeviceConnected(f:(address:QBluetoothAddress)=>void):void;
		DisconnectDeviceConnected():void;
		DeviceConnected(address:QBluetoothAddress_ITF):void;
		ConnectDeviceDisconnected(f:(address:QBluetoothAddress)=>void):void;
		DisconnectDeviceDisconnected():void;
		DeviceDisconnected(address:QBluetoothAddress_ITF):void;
		ConnectError(f:(error:number)=>void):void;
		DisconnectError():void;
		Error(error:number):void;
		HostMode():number;
		ConnectHostModeStateChanged(f:(state:number)=>void):void;
		DisconnectHostModeStateChanged():void;
		HostModeStateChanged(state:number):void;
		IsValid():boolean;
		Name():string;
		ConnectPairingConfirmation(f:(confirmation:boolean)=>void):void;
		DisconnectPairingConfirmation():void;
		PairingConfirmation(confirmation:boolean):void;
		PairingConfirmationDefault(confirmation:boolean):void;
		ConnectPairingDisplayConfirmation(f:(address:QBluetoothAddress,pi:string)=>void):void;
		DisconnectPairingDisplayConfirmation():void;
		PairingDisplayConfirmation(address:QBluetoothAddress_ITF,pi:string):void;
		ConnectPairingDisplayPinCode(f:(address:QBluetoothAddress,pi:string)=>void):void;
		DisconnectPairingDisplayPinCode():void;
		PairingDisplayPinCode(address:QBluetoothAddress_ITF,pi:string):void;
		ConnectPairingFinished(f:(address:QBluetoothAddress,pairing:number)=>void):void;
		DisconnectPairingFinished():void;
		PairingFinished(address:QBluetoothAddress_ITF,pairing:number):void;
		PairingStatus(address:QBluetoothAddress_ITF):number;
		PowerOn():void;
		RequestPairing(address:QBluetoothAddress_ITF,pairing:number):void;
		SetHostMode(mode:number):void;
		ConnectDestroyQBluetoothLocalDevice(f:()=>void):void;
		DisconnectDestroyQBluetoothLocalDevice():void;
		DestroyQBluetoothLocalDevice():void;
		DestroyQBluetoothLocalDeviceDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothLocalDeviceFromPointer(ptr:number):QBluetoothLocalDevice;
	function NewQBluetoothLocalDevice(parent:core.QObject_ITF):QBluetoothLocalDevice;
	function NewQBluetoothLocalDevice2(address:QBluetoothAddress_ITF,parent:core.QObject_ITF):QBluetoothLocalDevice;
	function QBluetoothLocalDevice_AllDevices():QBluetoothHostInfo[];
	const QBluetoothLocalDevice__Unpaired: number;
	const QBluetoothLocalDevice__Paired: number;
	const QBluetoothLocalDevice__AuthorizedPaired: number;
	const QBluetoothLocalDevice__HostPoweredOff: number;
	const QBluetoothLocalDevice__HostConnectable: number;
	const QBluetoothLocalDevice__HostDiscoverable: number;
	const QBluetoothLocalDevice__HostDiscoverableLimitedInquiry: number;
	const QBluetoothLocalDevice__NoError: number;
	const QBluetoothLocalDevice__PairingError: number;
	const QBluetoothLocalDevice__UnknownError: number;
	interface QBluetoothServer_ITF extends core.QObject_ITF {
		QBluetoothServer_PTR():QBluetoothServer;
	}

	class QBluetoothServer extends core.QObject {
		___pointer: number;
		QBluetoothServer_PTR():QBluetoothServer;
		Pointer():number;
		SetPointer(p:number):void;
		Close():void;
		Error():number;
		ConnectError2(f:(error:number)=>void):void;
		DisconnectError2():void;
		Error2(error:number):void;
		HasPendingConnections():boolean;
		IsListening():boolean;
		Listen(address:QBluetoothAddress_ITF,port:number):boolean;
		Listen2(uuid:QBluetoothUuid_ITF,serviceName:string):QBluetoothServiceInfo;
		MaxPendingConnections():number;
		ConnectNewConnection(f:()=>void):void;
		DisconnectNewConnection():void;
		NewConnection():void;
		NextPendingConnection():QBluetoothSocket;
		SecurityFlags():number;
		ServerAddress():QBluetoothAddress;
		ServerPort():number;
		ServerType():number;
		SetMaxPendingConnections(numConnections:number):void;
		SetSecurityFlags(security:number):void;
		ConnectDestroyQBluetoothServer(f:()=>void):void;
		DisconnectDestroyQBluetoothServer():void;
		DestroyQBluetoothServer():void;
		DestroyQBluetoothServerDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothServerFromPointer(ptr:number):QBluetoothServer;
	function NewQBluetoothServer(serverType:number,parent:core.QObject_ITF):QBluetoothServer;
	const QBluetoothServer__NoError: number;
	const QBluetoothServer__UnknownError: number;
	const QBluetoothServer__PoweredOffError: number;
	const QBluetoothServer__InputOutputError: number;
	const QBluetoothServer__ServiceAlreadyRegisteredError: number;
	const QBluetoothServer__UnsupportedProtocolError: number;
	interface QBluetoothServiceDiscoveryAgent_ITF extends core.QObject_ITF {
		QBluetoothServiceDiscoveryAgent_PTR():QBluetoothServiceDiscoveryAgent;
	}

	class QBluetoothServiceDiscoveryAgent extends core.QObject {
		___pointer: number;
		QBluetoothServiceDiscoveryAgent_PTR():QBluetoothServiceDiscoveryAgent;
		Pointer():number;
		SetPointer(p:number):void;
		ConnectCanceled(f:()=>void):void;
		DisconnectCanceled():void;
		Canceled():void;
		ConnectClear(f:()=>void):void;
		DisconnectClear():void;
		Clear():void;
		ClearDefault():void;
		DiscoveredServices():QBluetoothServiceInfo[];
		Error():number;
		ConnectError2(f:(error:number)=>void):void;
		DisconnectError2():void;
		Error2(error:number):void;
		ErrorString():string;
		ConnectFinished(f:()=>void):void;
		DisconnectFinished():void;
		Finished():void;
		IsActive():boolean;
		RemoteAddress():QBluetoothAddress;
		ConnectServiceDiscovered(f:(info:QBluetoothServiceInfo)=>void):void;
		DisconnectServiceDiscovered():void;
		ServiceDiscovered(info:QBluetoothServiceInfo_ITF):void;
		SetRemoteAddress(address:QBluetoothAddress_ITF):boolean;
		SetUuidFilter(uuids:QBluetoothUuid[]):void;
		SetUuidFilter2(uuid:QBluetoothUuid_ITF):void;
		ConnectStart(f:(mode:number)=>void):void;
		DisconnectStart():void;
		Start(mode:number):void;
		StartDefault(mode:number):void;
		ConnectStop(f:()=>void):void;
		DisconnectStop():void;
		Stop():void;
		StopDefault():void;
		UuidFilter():QBluetoothUuid[];
		ConnectDestroyQBluetoothServiceDiscoveryAgent(f:()=>void):void;
		DisconnectDestroyQBluetoothServiceDiscoveryAgent():void;
		DestroyQBluetoothServiceDiscoveryAgent():void;
		DestroyQBluetoothServiceDiscoveryAgentDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothServiceDiscoveryAgentFromPointer(ptr:number):QBluetoothServiceDiscoveryAgent;
	function NewQBluetoothServiceDiscoveryAgent(parent:core.QObject_ITF):QBluetoothServiceDiscoveryAgent;
	function NewQBluetoothServiceDiscoveryAgent2(deviceAdapter:QBluetoothAddress_ITF,parent:core.QObject_ITF):QBluetoothServiceDiscoveryAgent;
	const QBluetoothServiceDiscoveryAgent__NoError: number;
	const QBluetoothServiceDiscoveryAgent__InputOutputError: number;
	const QBluetoothServiceDiscoveryAgent__PoweredOffError: number;
	const QBluetoothServiceDiscoveryAgent__InvalidBluetoothAdapterError: number;
	const QBluetoothServiceDiscoveryAgent__UnknownError: number;
	const QBluetoothServiceDiscoveryAgent__MinimalDiscovery: number;
	const QBluetoothServiceDiscoveryAgent__FullDiscovery: number;
	interface QBluetoothServiceInfo_ITF {
		QBluetoothServiceInfo_PTR():QBluetoothServiceInfo;
	}

	class QBluetoothServiceInfo {
		___pointer: number;
		QBluetoothServiceInfo_PTR():QBluetoothServiceInfo;
		Pointer():number;
		SetPointer(p:number):void;
		Attribute(attributeId:number):core.QVariant;
		Contains(attributeId:number):boolean;
		Device():QBluetoothDeviceInfo;
		IsComplete():boolean;
		IsRegistered():boolean;
		IsValid():boolean;
		ProtocolServiceMultiplexer():number;
		RegisterService(localAdapter:QBluetoothAddress_ITF):boolean;
		RemoveAttribute(attributeId:number):void;
		ServerChannel():number;
		ServiceAvailability():string;
		ServiceClassUuids():QBluetoothUuid[];
		ServiceDescription():string;
		ServiceName():string;
		ServiceProvider():string;
		ServiceUuid():QBluetoothUuid;
		SetAttribute(attributeId:number,value:core.QVariant_ITF):void;
		SetAttribute2(attributeId:number,value:QBluetoothUuid_ITF):void;
		SetDevice(device:QBluetoothDeviceInfo_ITF):void;
		SetServiceAvailability(availability:string):void;
		SetServiceDescription(description:string):void;
		SetServiceName(name:string):void;
		SetServiceProvider(provider:string):void;
		SetServiceUuid(uuid:QBluetoothUuid_ITF):void;
		SocketProtocol():number;
		UnregisterService():boolean;
		DestroyQBluetoothServiceInfo():void;
	}
	function NewQBluetoothServiceInfoFromPointer(ptr:number):QBluetoothServiceInfo;
	function NewQBluetoothServiceInfo():QBluetoothServiceInfo;
	function NewQBluetoothServiceInfo2(other:QBluetoothServiceInfo_ITF):QBluetoothServiceInfo;
	const QBluetoothServiceInfo__ServiceRecordHandle: number;
	const QBluetoothServiceInfo__ServiceClassIds: number;
	const QBluetoothServiceInfo__ServiceRecordState: number;
	const QBluetoothServiceInfo__ServiceId: number;
	const QBluetoothServiceInfo__ProtocolDescriptorList: number;
	const QBluetoothServiceInfo__BrowseGroupList: number;
	const QBluetoothServiceInfo__LanguageBaseAttributeIdList: number;
	const QBluetoothServiceInfo__ServiceInfoTimeToLive: number;
	const QBluetoothServiceInfo__ServiceAvailability: number;
	const QBluetoothServiceInfo__BluetoothProfileDescriptorList: number;
	const QBluetoothServiceInfo__DocumentationUrl: number;
	const QBluetoothServiceInfo__ClientExecutableUrl: number;
	const QBluetoothServiceInfo__IconUrl: number;
	const QBluetoothServiceInfo__AdditionalProtocolDescriptorList: number;
	const QBluetoothServiceInfo__PrimaryLanguageBase: number;
	const QBluetoothServiceInfo__ServiceName: number;
	const QBluetoothServiceInfo__ServiceDescription: number;
	const QBluetoothServiceInfo__ServiceProvider: number;
	const QBluetoothServiceInfo__UnknownProtocol: number;
	const QBluetoothServiceInfo__L2capProtocol: number;
	const QBluetoothServiceInfo__RfcommProtocol: number;
	interface QBluetoothSocket_ITF extends core.QIODevice_ITF {
		QBluetoothSocket_PTR():QBluetoothSocket;
	}

	class QBluetoothSocket extends core.QIODevice {
		___pointer: number;
		QBluetoothSocket_PTR():QBluetoothSocket;
		Pointer():number;
		SetPointer(p:number):void;
		Abort():void;
		BytesAvailableDefault():number;
		BytesToWriteDefault():number;
		CanReadLineDefault():boolean;
		CloseDefault():void;
		ConnectToService(service:QBluetoothServiceInfo_ITF,openMode:number):void;
		ConnectToService2(address:QBluetoothAddress_ITF,uuid:QBluetoothUuid_ITF,openMode:number):void;
		ConnectToService3(address:QBluetoothAddress_ITF,port:number,openMode:number):void;
		ConnectConnected(f:()=>void):void;
		DisconnectConnected():void;
		Connected():void;
		DisconnectFromService():void;
		ConnectDisconnected(f:()=>void):void;
		DisconnectDisconnected():void;
		Disconnected():void;
		DoDeviceDiscovery(service:QBluetoothServiceInfo_ITF,openMode:number):void;
		Error():number;
		ConnectError2(f:(error:number)=>void):void;
		DisconnectError2():void;
		Error2(error:number):void;
		IsSequentialDefault():boolean;
		LocalAddress():QBluetoothAddress;
		LocalName():string;
		LocalPort():number;
		PeerAddress():QBluetoothAddress;
		PeerName():string;
		PeerPort():number;
		PreferredSecurityFlags():number;
		ConnectReadData(f:(data:string,maxSize:number)=>number):void;
		DisconnectReadData():void;
		ReadData(data:string,maxSize:number):number;
		ReadDataDefault(data:string,maxSize:number):number;
		SetPreferredSecurityFlags(flags:number):void;
		SetSocketDescriptor(socketDescriptor:number,socketType:number,socketState:number,openMode:number):boolean;
		SetSocketError(error_:number):void;
		SetSocketState(state:number):void;
		SocketDescriptor():number;
		SocketType():number;
		State():number;
		ConnectStateChanged(f:(state:number)=>void):void;
		DisconnectStateChanged():void;
		StateChanged(state:number):void;
		ConnectWriteData(f:(data:string,maxSize:number)=>number):void;
		DisconnectWriteData():void;
		WriteData(data:string,maxSize:number):number;
		WriteDataDefault(data:string,maxSize:number):number;
		ConnectDestroyQBluetoothSocket(f:()=>void):void;
		DisconnectDestroyQBluetoothSocket():void;
		DestroyQBluetoothSocket():void;
		DestroyQBluetoothSocketDefault():void;
		AtEndDefault():boolean;
		OpenDefault(mode:number):boolean;
		PosDefault():number;
		ReadLineDataDefault(data:string,maxSize:number):number;
		ResetDefault():boolean;
		SeekDefault(pos:number):boolean;
		SizeDefault():number;
		WaitForBytesWrittenDefault(msecs:number):boolean;
		WaitForReadyReadDefault(msecs:number):boolean;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothSocketFromPointer(ptr:number):QBluetoothSocket;
	function NewQBluetoothSocket(socketType:number,parent:core.QObject_ITF):QBluetoothSocket;
	function NewQBluetoothSocket2(parent:core.QObject_ITF):QBluetoothSocket;
	const QBluetoothSocket__UnconnectedState: number;
	const QBluetoothSocket__ServiceLookupState: number;
	const QBluetoothSocket__ConnectingState: number;
	const QBluetoothSocket__ConnectedState: number;
	const QBluetoothSocket__BoundState: number;
	const QBluetoothSocket__ClosingState: number;
	const QBluetoothSocket__ListeningState: number;
	const QBluetoothSocket__NoSocketError: number;
	const QBluetoothSocket__UnknownSocketError: number;
	const QBluetoothSocket__RemoteHostClosedError: number;
	const QBluetoothSocket__HostNotFoundError: number;
	const QBluetoothSocket__ServiceNotFoundError: number;
	const QBluetoothSocket__NetworkError: number;
	const QBluetoothSocket__UnsupportedProtocolError: number;
	const QBluetoothSocket__OperationError: number;
	interface QBluetoothTransferManager_ITF extends core.QObject_ITF {
		QBluetoothTransferManager_PTR():QBluetoothTransferManager;
	}

	class QBluetoothTransferManager extends core.QObject {
		___pointer: number;
		QBluetoothTransferManager_PTR():QBluetoothTransferManager;
		Pointer():number;
		SetPointer(p:number):void;
		ConnectFinished(f:(reply:QBluetoothTransferReply)=>void):void;
		DisconnectFinished():void;
		Finished(reply:QBluetoothTransferReply_ITF):void;
		Put(request:QBluetoothTransferRequest_ITF,data:core.QIODevice_ITF):QBluetoothTransferReply;
		ConnectDestroyQBluetoothTransferManager(f:()=>void):void;
		DisconnectDestroyQBluetoothTransferManager():void;
		DestroyQBluetoothTransferManager():void;
		DestroyQBluetoothTransferManagerDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothTransferManagerFromPointer(ptr:number):QBluetoothTransferManager;
	function NewQBluetoothTransferManager(parent:core.QObject_ITF):QBluetoothTransferManager;
	interface QBluetoothTransferReply_ITF extends core.QObject_ITF {
		QBluetoothTransferReply_PTR():QBluetoothTransferReply;
	}

	class QBluetoothTransferReply extends core.QObject {
		___pointer: number;
		QBluetoothTransferReply_PTR():QBluetoothTransferReply;
		Pointer():number;
		SetPointer(p:number):void;
		ConnectAbort(f:()=>void):void;
		DisconnectAbort():void;
		Abort():void;
		AbortDefault():void;
		ConnectError(f:()=>number):void;
		DisconnectError():void;
		Error():number;
		ConnectError2(f:(errorType:number)=>void):void;
		DisconnectError2():void;
		Error2(errorType:number):void;
		ConnectErrorString(f:()=>string):void;
		DisconnectErrorString():void;
		ErrorString():string;
		ConnectFinished(f:(reply:QBluetoothTransferReply)=>void):void;
		DisconnectFinished():void;
		Finished(reply:QBluetoothTransferReply_ITF):void;
		ConnectIsFinished(f:()=>boolean):void;
		DisconnectIsFinished():void;
		IsFinished():boolean;
		ConnectIsRunning(f:()=>boolean):void;
		DisconnectIsRunning():void;
		IsRunning():boolean;
		Manager():QBluetoothTransferManager;
		Request():QBluetoothTransferRequest;
		SetManager(manager:QBluetoothTransferManager_ITF):void;
		SetRequest(request:QBluetoothTransferRequest_ITF):void;
		ConnectTransferProgress(f:(bytesTransferred:number,bytesTotal:number)=>void):void;
		DisconnectTransferProgress():void;
		TransferProgress(bytesTransferred:number,bytesTotal:number):void;
		ConnectDestroyQBluetoothTransferReply(f:()=>void):void;
		DisconnectDestroyQBluetoothTransferReply():void;
		DestroyQBluetoothTransferReply():void;
		DestroyQBluetoothTransferReplyDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQBluetoothTransferReplyFromPointer(ptr:number):QBluetoothTransferReply;
	function NewQBluetoothTransferReply(parent:core.QObject_ITF):QBluetoothTransferReply;
	const QBluetoothTransferReply__NoError: number;
	const QBluetoothTransferReply__UnknownError: number;
	const QBluetoothTransferReply__FileNotFoundError: number;
	const QBluetoothTransferReply__HostNotFoundError: number;
	const QBluetoothTransferReply__UserCanceledTransferError: number;
	const QBluetoothTransferReply__IODeviceNotReadableError: number;
	const QBluetoothTransferReply__ResourceBusyError: number;
	const QBluetoothTransferReply__SessionError: number;
	interface QBluetoothTransferRequest_ITF {
		QBluetoothTransferRequest_PTR():QBluetoothTransferRequest;
	}

	class QBluetoothTransferRequest {
		___pointer: number;
		QBluetoothTransferRequest_PTR():QBluetoothTransferRequest;
		Pointer():number;
		SetPointer(p:number):void;
		Address():QBluetoothAddress;
		Attribute(code:number,defaultValue:core.QVariant_ITF):core.QVariant;
		SetAttribute(code:number,value:core.QVariant_ITF):void;
		DestroyQBluetoothTransferRequest():void;
	}
	function NewQBluetoothTransferRequestFromPointer(ptr:number):QBluetoothTransferRequest;
	function NewQBluetoothTransferRequest(address:QBluetoothAddress_ITF):QBluetoothTransferRequest;
	function NewQBluetoothTransferRequest2(other:QBluetoothTransferRequest_ITF):QBluetoothTransferRequest;
	const QBluetoothTransferRequest__DescriptionAttribute: number;
	const QBluetoothTransferRequest__TimeAttribute: number;
	const QBluetoothTransferRequest__TypeAttribute: number;
	const QBluetoothTransferRequest__LengthAttribute: number;
	const QBluetoothTransferRequest__NameAttribute: number;
	interface QBluetoothUuid_ITF extends core.QUuid_ITF {
		QBluetoothUuid_PTR():QBluetoothUuid;
	}

	class QBluetoothUuid extends core.QUuid {
		___pointer: number;
		QBluetoothUuid_PTR():QBluetoothUuid;
		Pointer():number;
		SetPointer(p:number):void;
		CharacteristicToString(uuid:number):string;
		DescriptorToString(uuid:number):string;
		MinimumSize():number;
		ProtocolToString(uuid:number):string;
		ServiceClassToString(uuid:number):string;
		ToUInt16(ok:boolean):number;
		ToUInt32(ok:boolean):number;
		DestroyQBluetoothUuid():void;
	}
	function NewQBluetoothUuidFromPointer(ptr:number):QBluetoothUuid;
	function NewQBluetoothUuid():QBluetoothUuid;
	function NewQBluetoothUuid2(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid3(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid4(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid5(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid6(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid7(uuid:number):QBluetoothUuid;
	function NewQBluetoothUuid9(uuid:string):QBluetoothUuid;
	function NewQBluetoothUuid10(uuid:QBluetoothUuid_ITF):QBluetoothUuid;
	function NewQBluetoothUuid11(uuid:core.QUuid_ITF):QBluetoothUuid;
	function QBluetoothUuid_CharacteristicToString(uuid:number):string;
	function QBluetoothUuid_DescriptorToString(uuid:number):string;
	function QBluetoothUuid_ProtocolToString(uuid:number):string;
	function QBluetoothUuid_ServiceClassToString(uuid:number):string;
	const QBluetoothUuid__Sdp: number;
	const QBluetoothUuid__Udp: number;
	const QBluetoothUuid__Rfcomm: number;
	const QBluetoothUuid__Tcp: number;
	const QBluetoothUuid__TcsBin: number;
	const QBluetoothUuid__TcsAt: number;
	const QBluetoothUuid__Att: number;
	const QBluetoothUuid__Obex: number;
	const QBluetoothUuid__Ip: number;
	const QBluetoothUuid__Ftp: number;
	const QBluetoothUuid__Http: number;
	const QBluetoothUuid__Wsp: number;
	const QBluetoothUuid__Bnep: number;
	const QBluetoothUuid__Upnp: number;
	const QBluetoothUuid__Hidp: number;
	const QBluetoothUuid__HardcopyControlChannel: number;
	const QBluetoothUuid__HardcopyDataChannel: number;
	const QBluetoothUuid__HardcopyNotification: number;
	const QBluetoothUuid__Avctp: number;
	const QBluetoothUuid__Avdtp: number;
	const QBluetoothUuid__Cmtp: number;
	const QBluetoothUuid__UdiCPlain: number;
	const QBluetoothUuid__McapControlChannel: number;
	const QBluetoothUuid__McapDataChannel: number;
	const QBluetoothUuid__L2cap: number;
	const QBluetoothUuid__ServiceDiscoveryServer: number;
	const QBluetoothUuid__BrowseGroupDescriptor: number;
	const QBluetoothUuid__PublicBrowseGroup: number;
	const QBluetoothUuid__SerialPort: number;
	const QBluetoothUuid__LANAccessUsingPPP: number;
	const QBluetoothUuid__DialupNetworking: number;
	const QBluetoothUuid__IrMCSync: number;
	const QBluetoothUuid__ObexObjectPush: number;
	const QBluetoothUuid__OBEXFileTransfer: number;
	const QBluetoothUuid__IrMCSyncCommand: number;
	const QBluetoothUuid__Headset: number;
	const QBluetoothUuid__AudioSource: number;
	const QBluetoothUuid__AudioSink: number;
	const QBluetoothUuid__AV_RemoteControlTarget: number;
	const QBluetoothUuid__AdvancedAudioDistribution: number;
	const QBluetoothUuid__AV_RemoteControl: number;
	const QBluetoothUuid__AV_RemoteControlController: number;
	const QBluetoothUuid__HeadsetAG: number;
	const QBluetoothUuid__PANU: number;
	const QBluetoothUuid__NAP: number;
	const QBluetoothUuid__GN: number;
	const QBluetoothUuid__DirectPrinting: number;
	const QBluetoothUuid__ReferencePrinting: number;
	const QBluetoothUuid__BasicImage: number;
	const QBluetoothUuid__ImagingResponder: number;
	const QBluetoothUuid__ImagingAutomaticArchive: number;
	const QBluetoothUuid__ImagingReferenceObjects: number;
	const QBluetoothUuid__Handsfree: number;
	const QBluetoothUuid__HandsfreeAudioGateway: number;
	const QBluetoothUuid__DirectPrintingReferenceObjectsService: number;
	const QBluetoothUuid__ReflectedUI: number;
	const QBluetoothUuid__BasicPrinting: number;
	const QBluetoothUuid__PrintingStatus: number;
	const QBluetoothUuid__HumanInterfaceDeviceService: number;
	const QBluetoothUuid__HardcopyCableReplacement: number;
	const QBluetoothUuid__HCRPrint: number;
	const QBluetoothUuid__HCRScan: number;
	const QBluetoothUuid__SIMAccess: number;
	const QBluetoothUuid__PhonebookAccessPCE: number;
	const QBluetoothUuid__PhonebookAccessPSE: number;
	const QBluetoothUuid__PhonebookAccess: number;
	const QBluetoothUuid__HeadsetHS: number;
	const QBluetoothUuid__MessageAccessServer: number;
	const QBluetoothUuid__MessageNotificationServer: number;
	const QBluetoothUuid__MessageAccessProfile: number;
	const QBluetoothUuid__GNSS: number;
	const QBluetoothUuid__GNSSServer: number;
	const QBluetoothUuid__Display3D: number;
	const QBluetoothUuid__Glasses3D: number;
	const QBluetoothUuid__Synchronization3D: number;
	const QBluetoothUuid__MPSProfile: number;
	const QBluetoothUuid__MPSService: number;
	const QBluetoothUuid__PnPInformation: number;
	const QBluetoothUuid__GenericNetworking: number;
	const QBluetoothUuid__GenericFileTransfer: number;
	const QBluetoothUuid__GenericAudio: number;
	const QBluetoothUuid__GenericTelephony: number;
	const QBluetoothUuid__VideoSource: number;
	const QBluetoothUuid__VideoSink: number;
	const QBluetoothUuid__VideoDistribution: number;
	const QBluetoothUuid__HDP: number;
	const QBluetoothUuid__HDPSource: number;
	const QBluetoothUuid__HDPSink: number;
	const QBluetoothUuid__GenericAccess: number;
	const QBluetoothUuid__GenericAttribute: number;
	const QBluetoothUuid__ImmediateAlert: number;
	const QBluetoothUuid__LinkLoss: number;
	const QBluetoothUuid__TxPower: number;
	const QBluetoothUuid__CurrentTimeService: number;
	const QBluetoothUuid__ReferenceTimeUpdateService: number;
	const QBluetoothUuid__NextDSTChangeService: number;
	const QBluetoothUuid__Glucose: number;
	const QBluetoothUuid__HealthThermometer: number;
	const QBluetoothUuid__DeviceInformation: number;
	const QBluetoothUuid__HeartRate: number;
	const QBluetoothUuid__PhoneAlertStatusService: number;
	const QBluetoothUuid__BatteryService: number;
	const QBluetoothUuid__BloodPressure: number;
	const QBluetoothUuid__AlertNotificationService: number;
	const QBluetoothUuid__HumanInterfaceDevice: number;
	const QBluetoothUuid__ScanParameters: number;
	const QBluetoothUuid__RunningSpeedAndCadence: number;
	const QBluetoothUuid__CyclingSpeedAndCadence: number;
	const QBluetoothUuid__CyclingPower: number;
	const QBluetoothUuid__LocationAndNavigation: number;
	const QBluetoothUuid__EnvironmentalSensing: number;
	const QBluetoothUuid__BodyComposition: number;
	const QBluetoothUuid__UserData: number;
	const QBluetoothUuid__WeightScale: number;
	const QBluetoothUuid__BondManagement: number;
	const QBluetoothUuid__ContinuousGlucoseMonitoring: number;
	const QBluetoothUuid__DeviceName: number;
	const QBluetoothUuid__Appearance: number;
	const QBluetoothUuid__PeripheralPrivacyFlag: number;
	const QBluetoothUuid__ReconnectionAddress: number;
	const QBluetoothUuid__PeripheralPreferredConnectionParameters: number;
	const QBluetoothUuid__ServiceChanged: number;
	const QBluetoothUuid__AlertLevel: number;
	const QBluetoothUuid__TxPowerLevel: number;
	const QBluetoothUuid__DateTime: number;
	const QBluetoothUuid__DayOfWeek: number;
	const QBluetoothUuid__DayDateTime: number;
	const QBluetoothUuid__ExactTime256: number;
	const QBluetoothUuid__DSTOffset: number;
	const QBluetoothUuid__TimeZone: number;
	const QBluetoothUuid__LocalTimeInformation: number;
	const QBluetoothUuid__TimeWithDST: number;
	const QBluetoothUuid__TimeAccuracy: number;
	const QBluetoothUuid__TimeSource: number;
	const QBluetoothUuid__ReferenceTimeInformation: number;
	const QBluetoothUuid__TimeUpdateControlPoint: number;
	const QBluetoothUuid__TimeUpdateState: number;
	const QBluetoothUuid__GlucoseMeasurement: number;
	const QBluetoothUuid__BatteryLevel: number;
	const QBluetoothUuid__TemperatureMeasurement: number;
	const QBluetoothUuid__TemperatureType: number;
	const QBluetoothUuid__IntermediateTemperature: number;
	const QBluetoothUuid__MeasurementInterval: number;
	const QBluetoothUuid__BootKeyboardInputReport: number;
	const QBluetoothUuid__SystemID: number;
	const QBluetoothUuid__ModelNumberString: number;
	const QBluetoothUuid__SerialNumberString: number;
	const QBluetoothUuid__FirmwareRevisionString: number;
	const QBluetoothUuid__HardwareRevisionString: number;
	const QBluetoothUuid__SoftwareRevisionString: number;
	const QBluetoothUuid__ManufacturerNameString: number;
	const QBluetoothUuid__IEEE1107320601RegulatoryCertificationDataList: number;
	const QBluetoothUuid__CurrentTime: number;
	const QBluetoothUuid__MagneticDeclination: number;
	const QBluetoothUuid__ScanRefresh: number;
	const QBluetoothUuid__BootKeyboardOutputReport: number;
	const QBluetoothUuid__BootMouseInputReport: number;
	const QBluetoothUuid__GlucoseMeasurementContext: number;
	const QBluetoothUuid__BloodPressureMeasurement: number;
	const QBluetoothUuid__IntermediateCuffPressure: number;
	const QBluetoothUuid__HeartRateMeasurement: number;
	const QBluetoothUuid__BodySensorLocation: number;
	const QBluetoothUuid__HeartRateControlPoint: number;
	const QBluetoothUuid__AlertStatus: number;
	const QBluetoothUuid__RingerControlPoint: number;
	const QBluetoothUuid__RingerSetting: number;
	const QBluetoothUuid__AlertCategoryIDBitMask: number;
	const QBluetoothUuid__AlertCategoryID: number;
	const QBluetoothUuid__AlertNotificationControlPoint: number;
	const QBluetoothUuid__UnreadAlertStatus: number;
	const QBluetoothUuid__NewAlert: number;
	const QBluetoothUuid__SupportedNewAlertCategory: number;
	const QBluetoothUuid__SupportedUnreadAlertCategory: number;
	const QBluetoothUuid__BloodPressureFeature: number;
	const QBluetoothUuid__HIDInformation: number;
	const QBluetoothUuid__ReportMap: number;
	const QBluetoothUuid__HIDControlPoint: number;
	const QBluetoothUuid__Report: number;
	const QBluetoothUuid__ProtocolMode: number;
	const QBluetoothUuid__ScanIntervalWindow: number;
	const QBluetoothUuid__PnPID: number;
	const QBluetoothUuid__GlucoseFeature: number;
	const QBluetoothUuid__RecordAccessControlPoint: number;
	const QBluetoothUuid__RSCMeasurement: number;
	const QBluetoothUuid__RSCFeature: number;
	const QBluetoothUuid__SCControlPoint: number;
	const QBluetoothUuid__CSCMeasurement: number;
	const QBluetoothUuid__CSCFeature: number;
	const QBluetoothUuid__SensorLocation: number;
	const QBluetoothUuid__CyclingPowerMeasurement: number;
	const QBluetoothUuid__CyclingPowerVector: number;
	const QBluetoothUuid__CyclingPowerFeature: number;
	const QBluetoothUuid__CyclingPowerControlPoint: number;
	const QBluetoothUuid__LocationAndSpeed: number;
	const QBluetoothUuid__Navigation: number;
	const QBluetoothUuid__PositionQuality: number;
	const QBluetoothUuid__LNFeature: number;
	const QBluetoothUuid__LNControlPoint: number;
	const QBluetoothUuid__Elevation: number;
	const QBluetoothUuid__Pressure: number;
	const QBluetoothUuid__Temperature: number;
	const QBluetoothUuid__Humidity: number;
	const QBluetoothUuid__TrueWindSpeed: number;
	const QBluetoothUuid__TrueWindDirection: number;
	const QBluetoothUuid__ApparentWindSpeed: number;
	const QBluetoothUuid__ApparentWindDirection: number;
	const QBluetoothUuid__GustFactor: number;
	const QBluetoothUuid__PollenConcentration: number;
	const QBluetoothUuid__UVIndex: number;
	const QBluetoothUuid__Irradiance: number;
	const QBluetoothUuid__Rainfall: number;
	const QBluetoothUuid__WindChill: number;
	const QBluetoothUuid__HeatIndex: number;
	const QBluetoothUuid__DewPoint: number;
	const QBluetoothUuid__DescriptorValueChanged: number;
	const QBluetoothUuid__AerobicHeartRateLowerLimit: number;
	const QBluetoothUuid__AerobicThreshold: number;
	const QBluetoothUuid__Age: number;
	const QBluetoothUuid__AnaerobicHeartRateLowerLimit: number;
	const QBluetoothUuid__AnaerobicHeartRateUpperLimit: number;
	const QBluetoothUuid__AnaerobicThreshold: number;
	const QBluetoothUuid__AerobicHeartRateUpperLimit: number;
	const QBluetoothUuid__DateOfBirth: number;
	const QBluetoothUuid__DateOfThresholdAssessment: number;
	const QBluetoothUuid__EmailAddress: number;
	const QBluetoothUuid__FatBurnHeartRateLowerLimit: number;
	const QBluetoothUuid__FatBurnHeartRateUpperLimit: number;
	const QBluetoothUuid__FirstName: number;
	const QBluetoothUuid__FiveZoneHeartRateLimits: number;
	const QBluetoothUuid__Gender: number;
	const QBluetoothUuid__HeartRateMax: number;
	const QBluetoothUuid__Height: number;
	const QBluetoothUuid__HipCircumference: number;
	const QBluetoothUuid__LastName: number;
	const QBluetoothUuid__MaximumRecommendedHeartRate: number;
	const QBluetoothUuid__RestingHeartRate: number;
	const QBluetoothUuid__SportTypeForAerobicAnaerobicThresholds: number;
	const QBluetoothUuid__ThreeZoneHeartRateLimits: number;
	const QBluetoothUuid__TwoZoneHeartRateLimits: number;
	const QBluetoothUuid__VO2Max: number;
	const QBluetoothUuid__WaistCircumference: number;
	const QBluetoothUuid__Weight: number;
	const QBluetoothUuid__DatabaseChangeIncrement: number;
	const QBluetoothUuid__UserIndex: number;
	const QBluetoothUuid__BodyCompositionFeature: number;
	const QBluetoothUuid__BodyCompositionMeasurement: number;
	const QBluetoothUuid__WeightMeasurement: number;
	const QBluetoothUuid__WeightScaleFeature: number;
	const QBluetoothUuid__UserControlPoint: number;
	const QBluetoothUuid__MagneticFluxDensity2D: number;
	const QBluetoothUuid__MagneticFluxDensity3D: number;
	const QBluetoothUuid__Language: number;
	const QBluetoothUuid__BarometricPressureTrend: number;
	const QBluetoothUuid__UnknownDescriptorType: number;
	const QBluetoothUuid__CharacteristicExtendedProperties: number;
	const QBluetoothUuid__CharacteristicUserDescription: number;
	const QBluetoothUuid__ClientCharacteristicConfiguration: number;
	const QBluetoothUuid__ServerCharacteristicConfiguration: number;
	const QBluetoothUuid__CharacteristicPresentationFormat: number;
	const QBluetoothUuid__CharacteristicAggregateFormat: number;
	const QBluetoothUuid__ValidRange: number;
	const QBluetoothUuid__ExternalReportReference: number;
	const QBluetoothUuid__ReportReference: number;
	const QBluetoothUuid__EnvironmentalSensingConfiguration: number;
	const QBluetoothUuid__EnvironmentalSensingMeasurement: number;
	const QBluetoothUuid__EnvironmentalSensingTriggerSetting: number;
	interface QLowEnergyAdvertisingData_ITF {
		QLowEnergyAdvertisingData_PTR():QLowEnergyAdvertisingData;
	}

	class QLowEnergyAdvertisingData {
		___pointer: number;
		QLowEnergyAdvertisingData_PTR():QLowEnergyAdvertisingData;
		Pointer():number;
		SetPointer(p:number):void;
		Discoverability():number;
		IncludePowerLevel():boolean;
		InvalidManufacturerId():number;
		LocalName():string;
		ManufacturerId():number;
		RawData():core.QByteArray;
		Services():QBluetoothUuid[];
		SetDiscoverability(mode:number):void;
		SetIncludePowerLevel(doInclude:boolean):void;
		SetLocalName(name:string):void;
		SetManufacturerData(id:number,data:core.QByteArray_ITF):void;
		SetRawData(data:core.QByteArray_ITF):void;
		SetServices(services:QBluetoothUuid[]):void;
		Swap(other:QLowEnergyAdvertisingData_ITF):void;
		DestroyQLowEnergyAdvertisingData():void;
	}
	function NewQLowEnergyAdvertisingDataFromPointer(ptr:number):QLowEnergyAdvertisingData;
	function NewQLowEnergyAdvertisingData():QLowEnergyAdvertisingData;
	function NewQLowEnergyAdvertisingData2(other:QLowEnergyAdvertisingData_ITF):QLowEnergyAdvertisingData;
	function QLowEnergyAdvertisingData_InvalidManufacturerId():number;
	const QLowEnergyAdvertisingData__DiscoverabilityNone: number;
	const QLowEnergyAdvertisingData__DiscoverabilityLimited: number;
	const QLowEnergyAdvertisingData__DiscoverabilityGeneral: number;
	interface QLowEnergyAdvertisingParameters_ITF {
		QLowEnergyAdvertisingParameters_PTR():QLowEnergyAdvertisingParameters;
	}

	class QLowEnergyAdvertisingParameters {
		___pointer: number;
		QLowEnergyAdvertisingParameters_PTR():QLowEnergyAdvertisingParameters;
		Pointer():number;
		SetPointer(p:number):void;
		FilterPolicy():number;
		MaximumInterval():number;
		MinimumInterval():number;
		Mode():number;
		SetInterval(minimum:number,maximum:number):void;
		SetMode(mode:number):void;
		Swap(other:QLowEnergyAdvertisingParameters_ITF):void;
		DestroyQLowEnergyAdvertisingParameters():void;
	}
	function NewQLowEnergyAdvertisingParametersFromPointer(ptr:number):QLowEnergyAdvertisingParameters;
	function NewQLowEnergyAdvertisingParameters():QLowEnergyAdvertisingParameters;
	function NewQLowEnergyAdvertisingParameters2(other:QLowEnergyAdvertisingParameters_ITF):QLowEnergyAdvertisingParameters;
	const QLowEnergyAdvertisingParameters__AdvInd: number;
	const QLowEnergyAdvertisingParameters__AdvScanInd: number;
	const QLowEnergyAdvertisingParameters__AdvNonConnInd: number;
	const QLowEnergyAdvertisingParameters__IgnoreWhiteList: number;
	const QLowEnergyAdvertisingParameters__UseWhiteListForScanning: number;
	const QLowEnergyAdvertisingParameters__UseWhiteListForConnecting: number;
	const QLowEnergyAdvertisingParameters__UseWhiteListForScanningAndConnecting: number;
	interface QLowEnergyCharacteristic_ITF {
		QLowEnergyCharacteristic_PTR():QLowEnergyCharacteristic;
	}

	class QLowEnergyCharacteristic {
		___pointer: number;
		QLowEnergyCharacteristic_PTR():QLowEnergyCharacteristic;
		Pointer():number;
		SetPointer(p:number):void;
		Descriptor(uuid:QBluetoothUuid_ITF):QLowEnergyDescriptor;
		Descriptors():QLowEnergyDescriptor[];
		IsValid():boolean;
		Name():string;
		Properties():number;
		Uuid():QBluetoothUuid;
		Value():core.QByteArray;
		DestroyQLowEnergyCharacteristic():void;
	}
	function NewQLowEnergyCharacteristicFromPointer(ptr:number):QLowEnergyCharacteristic;
	function NewQLowEnergyCharacteristic():QLowEnergyCharacteristic;
	function NewQLowEnergyCharacteristic2(other:QLowEnergyCharacteristic_ITF):QLowEnergyCharacteristic;
	const QLowEnergyCharacteristic__Unknown: number;
	const QLowEnergyCharacteristic__Broadcasting: number;
	const QLowEnergyCharacteristic__Read: number;
	const QLowEnergyCharacteristic__WriteNoResponse: number;
	const QLowEnergyCharacteristic__Write: number;
	const QLowEnergyCharacteristic__Notify: number;
	const QLowEnergyCharacteristic__Indicate: number;
	const QLowEnergyCharacteristic__WriteSigned: number;
	const QLowEnergyCharacteristic__ExtendedProperty: number;
	interface QLowEnergyCharacteristicData_ITF {
		QLowEnergyCharacteristicData_PTR():QLowEnergyCharacteristicData;
	}

	class QLowEnergyCharacteristicData {
		___pointer: number;
		QLowEnergyCharacteristicData_PTR():QLowEnergyCharacteristicData;
		Pointer():number;
		SetPointer(p:number):void;
		AddDescriptor(descriptor:QLowEnergyDescriptorData_ITF):void;
		Descriptors():QLowEnergyDescriptorData[];
		IsValid():boolean;
		MaximumValueLength():number;
		MinimumValueLength():number;
		Properties():number;
		ReadConstraints():number;
		SetDescriptors(descriptors:QLowEnergyDescriptorData[]):void;
		SetProperties(properties:number):void;
		SetReadConstraints(constraints:number):void;
		SetUuid(uuid:QBluetoothUuid_ITF):void;
		SetValue(value:core.QByteArray_ITF):void;
		SetValueLength(minimum:number,maximum:number):void;
		SetWriteConstraints(constraints:number):void;
		Swap(other:QLowEnergyCharacteristicData_ITF):void;
		Uuid():QBluetoothUuid;
		Value():core.QByteArray;
		WriteConstraints():number;
		DestroyQLowEnergyCharacteristicData():void;
	}
	function NewQLowEnergyCharacteristicDataFromPointer(ptr:number):QLowEnergyCharacteristicData;
	function NewQLowEnergyCharacteristicData():QLowEnergyCharacteristicData;
	function NewQLowEnergyCharacteristicData2(other:QLowEnergyCharacteristicData_ITF):QLowEnergyCharacteristicData;
	interface QLowEnergyConnectionParameters_ITF {
		QLowEnergyConnectionParameters_PTR():QLowEnergyConnectionParameters;
	}

	class QLowEnergyConnectionParameters {
		___pointer: number;
		QLowEnergyConnectionParameters_PTR():QLowEnergyConnectionParameters;
		Pointer():number;
		SetPointer(p:number):void;
		Latency():number;
		MaximumInterval():number;
		MinimumInterval():number;
		SetIntervalRange(minimum:number,maximum:number):void;
		SetLatency(latency:number):void;
		SetSupervisionTimeout(timeout:number):void;
		SupervisionTimeout():number;
		Swap(other:QLowEnergyConnectionParameters_ITF):void;
		DestroyQLowEnergyConnectionParameters():void;
	}
	function NewQLowEnergyConnectionParametersFromPointer(ptr:number):QLowEnergyConnectionParameters;
	function NewQLowEnergyConnectionParameters():QLowEnergyConnectionParameters;
	function NewQLowEnergyConnectionParameters2(other:QLowEnergyConnectionParameters_ITF):QLowEnergyConnectionParameters;
	interface QLowEnergyController_ITF extends core.QObject_ITF {
		QLowEnergyController_PTR():QLowEnergyController;
	}

	class QLowEnergyController extends core.QObject {
		___pointer: number;
		QLowEnergyController_PTR():QLowEnergyController;
		Pointer():number;
		SetPointer(p:number):void;
		AddService(service:QLowEnergyServiceData_ITF,parent:core.QObject_ITF):QLowEnergyService;
		ConnectToDevice():void;
		ConnectConnected(f:()=>void):void;
		DisconnectConnected():void;
		Connected():void;
		ConnectConnectionUpdated(f:(newParameters:QLowEnergyConnectionParameters)=>void):void;
		DisconnectConnectionUpdated():void;
		ConnectionUpdated(newParameters:QLowEnergyConnectionParameters_ITF):void;
		CreateCentral(remoteDevice:QBluetoothDeviceInfo_ITF,parent:core.QObject_ITF):QLowEnergyController;
		CreatePeripheral(parent:core.QObject_ITF):QLowEnergyController;
		CreateServiceObject(serviceUuid:QBluetoothUuid_ITF,parent:core.QObject_ITF):QLowEnergyService;
		DisconnectFromDevice():void;
		ConnectDisconnected(f:()=>void):void;
		DisconnectDisconnected():void;
		Disconnected():void;
		DiscoverServices():void;
		ConnectDiscoveryFinished(f:()=>void):void;
		DisconnectDiscoveryFinished():void;
		DiscoveryFinished():void;
		Error():number;
		ConnectError2(f:(newError:number)=>void):void;
		DisconnectError2():void;
		Error2(newError:number):void;
		ErrorString():string;
		LocalAddress():QBluetoothAddress;
		RemoteAddress():QBluetoothAddress;
		RemoteAddressType():number;
		RemoteDeviceUuid():QBluetoothUuid;
		RemoteName():string;
		RequestConnectionUpdate(parameters:QLowEnergyConnectionParameters_ITF):void;
		Role():number;
		ConnectServiceDiscovered(f:(newService:QBluetoothUuid)=>void):void;
		DisconnectServiceDiscovered():void;
		ServiceDiscovered(newService:QBluetoothUuid_ITF):void;
		Services():QBluetoothUuid[];
		SetRemoteAddressType(ty:number):void;
		StartAdvertising(parameters:QLowEnergyAdvertisingParameters_ITF,advertisingData:QLowEnergyAdvertisingData_ITF,scanResponseData:QLowEnergyAdvertisingData_ITF):void;
		State():number;
		ConnectStateChanged(f:(state:number)=>void):void;
		DisconnectStateChanged():void;
		StateChanged(state:number):void;
		StopAdvertising():void;
		ConnectDestroyQLowEnergyController(f:()=>void):void;
		DisconnectDestroyQLowEnergyController():void;
		DestroyQLowEnergyController():void;
		DestroyQLowEnergyControllerDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQLowEnergyControllerFromPointer(ptr:number):QLowEnergyController;
	function QLowEnergyController_CreateCentral(remoteDevice:QBluetoothDeviceInfo_ITF,parent:core.QObject_ITF):QLowEnergyController;
	function QLowEnergyController_CreatePeripheral(parent:core.QObject_ITF):QLowEnergyController;
	const QLowEnergyController__NoError: number;
	const QLowEnergyController__UnknownError: number;
	const QLowEnergyController__UnknownRemoteDeviceError: number;
	const QLowEnergyController__NetworkError: number;
	const QLowEnergyController__InvalidBluetoothAdapterError: number;
	const QLowEnergyController__ConnectionError: number;
	const QLowEnergyController__AdvertisingError: number;
	const QLowEnergyController__RemoteHostClosedError: number;
	const QLowEnergyController__UnconnectedState: number;
	const QLowEnergyController__ConnectingState: number;
	const QLowEnergyController__ConnectedState: number;
	const QLowEnergyController__DiscoveringState: number;
	const QLowEnergyController__DiscoveredState: number;
	const QLowEnergyController__ClosingState: number;
	const QLowEnergyController__AdvertisingState: number;
	const QLowEnergyController__PublicAddress: number;
	const QLowEnergyController__RandomAddress: number;
	const QLowEnergyController__CentralRole: number;
	const QLowEnergyController__PeripheralRole: number;
	interface QLowEnergyDescriptor_ITF {
		QLowEnergyDescriptor_PTR():QLowEnergyDescriptor;
	}

	class QLowEnergyDescriptor {
		___pointer: number;
		QLowEnergyDescriptor_PTR():QLowEnergyDescriptor;
		Pointer():number;
		SetPointer(p:number):void;
		IsValid():boolean;
		Name():string;
		Type():number;
		Uuid():QBluetoothUuid;
		Value():core.QByteArray;
		DestroyQLowEnergyDescriptor():void;
	}
	function NewQLowEnergyDescriptorFromPointer(ptr:number):QLowEnergyDescriptor;
	function NewQLowEnergyDescriptor():QLowEnergyDescriptor;
	function NewQLowEnergyDescriptor2(other:QLowEnergyDescriptor_ITF):QLowEnergyDescriptor;
	interface QLowEnergyDescriptorData_ITF {
		QLowEnergyDescriptorData_PTR():QLowEnergyDescriptorData;
	}

	class QLowEnergyDescriptorData {
		___pointer: number;
		QLowEnergyDescriptorData_PTR():QLowEnergyDescriptorData;
		Pointer():number;
		SetPointer(p:number):void;
		IsReadable():boolean;
		IsValid():boolean;
		IsWritable():boolean;
		ReadConstraints():number;
		SetReadPermissions(readable:boolean,constraints:number):void;
		SetUuid(uuid:QBluetoothUuid_ITF):void;
		SetValue(value:core.QByteArray_ITF):void;
		SetWritePermissions(writable:boolean,constraints:number):void;
		Swap(other:QLowEnergyDescriptorData_ITF):void;
		Uuid():QBluetoothUuid;
		Value():core.QByteArray;
		WriteConstraints():number;
		DestroyQLowEnergyDescriptorData():void;
	}
	function NewQLowEnergyDescriptorDataFromPointer(ptr:number):QLowEnergyDescriptorData;
	function NewQLowEnergyDescriptorData():QLowEnergyDescriptorData;
	function NewQLowEnergyDescriptorData2(uuid:QBluetoothUuid_ITF,value:core.QByteArray_ITF):QLowEnergyDescriptorData;
	function NewQLowEnergyDescriptorData3(other:QLowEnergyDescriptorData_ITF):QLowEnergyDescriptorData;
	interface QLowEnergyService_ITF extends core.QObject_ITF {
		QLowEnergyService_PTR():QLowEnergyService;
	}

	class QLowEnergyService extends core.QObject {
		___pointer: number;
		QLowEnergyService_PTR():QLowEnergyService;
		Pointer():number;
		SetPointer(p:number):void;
		Characteristic(uuid:QBluetoothUuid_ITF):QLowEnergyCharacteristic;
		ConnectCharacteristicChanged(f:(characteristic:QLowEnergyCharacteristic,newValue:core.QByteArray)=>void):void;
		DisconnectCharacteristicChanged():void;
		CharacteristicChanged(characteristic:QLowEnergyCharacteristic_ITF,newValue:core.QByteArray_ITF):void;
		ConnectCharacteristicRead(f:(characteristic:QLowEnergyCharacteristic,value:core.QByteArray)=>void):void;
		DisconnectCharacteristicRead():void;
		CharacteristicRead(characteristic:QLowEnergyCharacteristic_ITF,value:core.QByteArray_ITF):void;
		ConnectCharacteristicWritten(f:(characteristic:QLowEnergyCharacteristic,newValue:core.QByteArray)=>void):void;
		DisconnectCharacteristicWritten():void;
		CharacteristicWritten(characteristic:QLowEnergyCharacteristic_ITF,newValue:core.QByteArray_ITF):void;
		Characteristics():QLowEnergyCharacteristic[];
		Contains(characteristic:QLowEnergyCharacteristic_ITF):boolean;
		Contains2(descriptor:QLowEnergyDescriptor_ITF):boolean;
		ConnectDescriptorRead(f:(descriptor:QLowEnergyDescriptor,value:core.QByteArray)=>void):void;
		DisconnectDescriptorRead():void;
		DescriptorRead(descriptor:QLowEnergyDescriptor_ITF,value:core.QByteArray_ITF):void;
		ConnectDescriptorWritten(f:(descriptor:QLowEnergyDescriptor,newValue:core.QByteArray)=>void):void;
		DisconnectDescriptorWritten():void;
		DescriptorWritten(descriptor:QLowEnergyDescriptor_ITF,newValue:core.QByteArray_ITF):void;
		DiscoverDetails():void;
		Error():number;
		ConnectError2(f:(newError:number)=>void):void;
		DisconnectError2():void;
		Error2(newError:number):void;
		IncludedServices():QBluetoothUuid[];
		ReadCharacteristic(characteristic:QLowEnergyCharacteristic_ITF):void;
		ReadDescriptor(descriptor:QLowEnergyDescriptor_ITF):void;
		ServiceName():string;
		ServiceUuid():QBluetoothUuid;
		State():number;
		ConnectStateChanged(f:(newState:number)=>void):void;
		DisconnectStateChanged():void;
		StateChanged(newState:number):void;
		Type():number;
		WriteCharacteristic(characteristic:QLowEnergyCharacteristic_ITF,newValue:core.QByteArray_ITF,mode:number):void;
		WriteDescriptor(descriptor:QLowEnergyDescriptor_ITF,newValue:core.QByteArray_ITF):void;
		ConnectDestroyQLowEnergyService(f:()=>void):void;
		DisconnectDestroyQLowEnergyService():void;
		DestroyQLowEnergyService():void;
		DestroyQLowEnergyServiceDefault():void;
		ChildEventDefault(event:core.QChildEvent_ITF):void;
		ConnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		CustomEventDefault(event:core.QEvent_ITF):void;
		DeleteLaterDefault():void;
		DisconnectNotifyDefault(sign:core.QMetaMethod_ITF):void;
		EventDefault(e:core.QEvent_ITF):boolean;
		EventFilterDefault(watched:core.QObject_ITF,event:core.QEvent_ITF):boolean;
		MetaObjectDefault():core.QMetaObject;
		TimerEventDefault(event:core.QTimerEvent_ITF):void;
	}
	function NewQLowEnergyServiceFromPointer(ptr:number):QLowEnergyService;
	const QLowEnergyService__PrimaryService: number;
	const QLowEnergyService__IncludedService: number;
	const QLowEnergyService__NoError: number;
	const QLowEnergyService__OperationError: number;
	const QLowEnergyService__CharacteristicWriteError: number;
	const QLowEnergyService__DescriptorWriteError: number;
	const QLowEnergyService__UnknownError: number;
	const QLowEnergyService__CharacteristicReadError: number;
	const QLowEnergyService__DescriptorReadError: number;
	const QLowEnergyService__InvalidService: number;
	const QLowEnergyService__DiscoveryRequired: number;
	const QLowEnergyService__DiscoveringServices: number;
	const QLowEnergyService__ServiceDiscovered: number;
	const QLowEnergyService__LocalService: number;
	const QLowEnergyService__WriteWithResponse: number;
	const QLowEnergyService__WriteWithoutResponse: number;
	const QLowEnergyService__WriteSigned: number;
	interface QLowEnergyServiceData_ITF {
		QLowEnergyServiceData_PTR():QLowEnergyServiceData;
	}

	class QLowEnergyServiceData {
		___pointer: number;
		QLowEnergyServiceData_PTR():QLowEnergyServiceData;
		Pointer():number;
		SetPointer(p:number):void;
		AddCharacteristic(characteristic:QLowEnergyCharacteristicData_ITF):void;
		AddIncludedService(service:QLowEnergyService_ITF):void;
		Characteristics():QLowEnergyCharacteristicData[];
		IncludedServices():QLowEnergyService[];
		IsValid():boolean;
		SetCharacteristics(characteristics:QLowEnergyCharacteristicData[]):void;
		SetIncludedServices(services:QLowEnergyService[]):void;
		SetType(ty:number):void;
		SetUuid(uuid:QBluetoothUuid_ITF):void;
		Swap(other:QLowEnergyServiceData_ITF):void;
		Type():number;
		Uuid():QBluetoothUuid;
		DestroyQLowEnergyServiceData():void;
	}
	function NewQLowEnergyServiceDataFromPointer(ptr:number):QLowEnergyServiceData;
	function NewQLowEnergyServiceData():QLowEnergyServiceData;
	function NewQLowEnergyServiceData2(other:QLowEnergyServiceData_ITF):QLowEnergyServiceData;
	const QLowEnergyServiceData__ServiceTypePrimary: number;
	const QLowEnergyServiceData__ServiceTypeSecondary: number;
}